"""empty message

Revision ID: a82581816a20
Revises: 7c18ca01681b
Create Date: 2025-12-24 19:48:13.908202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a82581816a20'
down_revision: Union[str, Sequence[str], None] = '7c18ca01681b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themes_name'), table_name='themes')
    op.create_unique_constraint(None, 'themes', ['name'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'themes', type_='unique')
    op.create_index(op.f('ix_themes_name'), 'themes', ['name'], unique=True)
    # ### end Alembic commands ###
