"""empty message

Revision ID: c17b46189926
Revises: 0f3f5fe8ae4b
Create Date: 2025-12-18 00:46:17.386146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c17b46189926'
down_revision: Union[str, Sequence[str], None] = '0f3f5fe8ae4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auths', 'aux_token')
    op.drop_column('auths', 'refresh_token')
    op.alter_column('users', 'picture',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('auths', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('auths', sa.Column('aux_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
